### ISSUE TITLE
database unable to download

### ISSUE THREAD

**Issue by hujingchu** [cougarlj/COMPSRA#1]
database unable to download

**Comment by cougarlj** [comment]
Hi, hujingchu,

Thank you for the feedback. Would you like to provide more description about this issue? Which database couldn't you download?

Best Wishes,
  Jiang

**Comment by hujingchu** [comment]
Hi Jiang,
The pre-build database doesn't exists, for example:[https://regepi.bwh.harvard.edu/circurna/bundle_v1/prebuilt_db/miRBase_hg38.obj](https://regepi.bwh.harvard.edu/circurna/bundle_v1/prebuilt_db/miRBase_hg38.obj)

**Comment by cougarlj** [comment]
Hi, huijingchu,

I found the database files disappeared and didn't know why it happened. Finally, I have upload these pre-built database and it does work. If any questions, let me know. 

Best Wishes,
  Jiang
