### ISSUE TITLE
issue in function module

### ISSUE THREAD

**Issue by sayamsmr** [cougarlj/COMPSRA#17]
Hello, 
I find the pipeline to be quite useful and convenient. It would be great if you can provide a sample of how the sample.list file should be, the pipeline is working fine for me till i use single file as input, but after the annotation module I wanted to perform DEG analysis for pirnas, can you provide me some insights in merging the count files for pirnas??

This is the sample.list file prepared by me :
/example_out/sample02/sample02_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample04/sample04_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample05/sample05_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample06/sample06_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample07/sample07_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample08/sample08_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample11/sample11_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample12/sample12_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample13/sample13_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample14/sample14_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample15/sample15_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample16/sample16_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample17/sample17_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample18/sample18_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample09/sample09_17to35_FitRead_STAR_Aligned_piRNA.txt
/example_out/sample10/sample10_17to35_FitRead_STAR_Aligned_piRNA.txt

COMPSRA-master2$java -jar COMPSRA.jar -ref hg38 -fun -fd -fdclass 2 -fdcase 1-14 -fdctrl 15-16 -fdnorm cpm -fdtest mwu -fdann -pro COMPSRA_DEG -inf sample.list -out ./example_out/

Error: 07:43:50.617 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.fun.DEG - Class Parse ---> OK!
07:43:50.617 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.fun.DEG - Test Parse ---> OK!
07:43:50.618 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.fun.DEG - Sample Parse ---> OK!
07:43:50.620 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.fun.DEG - DEG was failed to run.
07:43:50.622 [main] INFO  edu.harvard.channing.compass.core.Produce - Function module was completed.

Thank You

**Comment by cougarlj** [comment]
Dear sayamsmr,

Thank you for using COMPSRA in your research. 
To run a single sample, you can use the parameter "-in" and provide the full path of the sample. 
To merge the count files together, you can use the Toolkit in COMPSRA. The method I usually take is to get the count files from Shell and then merge them together through COMPSRA. I will give the code that you can refer to as fellows. 

find /fullpath/example_out/ -name *_piRNA.txt | sort > /fullpath/example_out/your_sample.txt
java -jar COMPSRA.jar -tk -merge -id 0 -count 2 -inf /fullpath/example_out/your_sample.txt -out /fullpath/example_out/your_sample_piRNA_count.txt

The DEG function in COMPSRA is very simple (will be enhanced in the future version), so I suggest you to perform DEG in R where you can choose different statistical tests. 

If you have any problem, please let me know. 

Best Wishes,
  Jiang Li

**Comment by sayamsmr** [comment]
Thank You
