### ISSUE TITLE
error in annotation 

### ISSUE THREAD

**Issue by mars188** [cougarlj/COMPSRA#23]
Hello, 

I performed all the previous steps (QC, alignment) that seemed to go well but I get the following error while running the annotation module. 

"The prebuilt database file /scratch/gencore/ma5877/small_RNA/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg38.obj doesn't exist!"

Here is my script:
`java -jar COMPSRA.jar -ref hg38 -ann -ac 1,2,3,4,5,6 -in ./example_out/sample01/sample01_17to50_FitRead_STAR_Aligned.out.bam -out ./example_out/sample01/sample01_17to50_FitRead_STAR_Aligned`

Even though miRBase.hg38.obj is there on the shown path. It is somehow not reading it. 

Please help me in solving this issue. Thanks

**Comment by mars188** [comment]
Here is the complete error message:

`Working Directory: /scratch/gencore/ma5877/small_RNA/COMPSRA
Bundle Directory: /scratch/gencore/ma5877/small_RNA/COMPSRA/bundle_v1
Configuration Directory: /scratch/gencore/ma5877/small_RNA/COMPSRA/bundle_v1/configuration
Plug Directory: /scratch/gencore/ma5877/small_RNA/COMPSRA/bundle_v1/plug
N_CPU: 28

Configuration Info: The endogenous database configuration has been set!
Configuration Info: 37 databases are set!
15:59:45.748 [main] INFO  edu.harvard.channing.compass.core.Configuration - The Configuration was completed!

The hg38 reference genome was set.
QC module will not be performed.
Alignment module will not be performed.
Microbe module will not be performed.
Function module will not be performed.

+++++++++++++++++++++++++++++++
+   Module  --->  Annotation  +
+++++++++++++++++++++++++++++++

DEBUG   2021-09-09 15:59:45     BlockCompressedOutputStream     Using deflater: Deflater
15:59:45.964 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - edu.harvard.channing.compass.entity.DBTree; local class incompatible: stream classdesc serialVersionUID = 556476181312992002, local class serialVersionUID = 1386352989058994328
15:59:45.966 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - Fail to find the prebuilt database obj file!
15:59:45.966 [pool-2-thread-1] WARN  edu.harvard.channing.compass.db.DB_miRBase - The prebuilt database file /scratch/gencore/ma5877/small_RNA/COMPSRA/bundle_v1/prebuilt_db/miRBase_hg38.obj doesn't exist!
15:59:45.966 [pool-2-thread-1] INFO  edu.harvard.channing.compass.db.DB_miRBase - Try to build the database from local files /scratch/gencore/ma5877/small_RNA/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3 !
15:59:45.967 [pool-2-thread-1] INFO  edu.harvard.channing.compass.core.Factory - Read File Error: Fail to read file: miRBase_v21
15:59:45.967 [pool-2-thread-1] ERROR edu.harvard.channing.compass.utility.ReadFile - null
15:59:45.967 [pool-2-thread-1] INFO  edu.harvard.channing.compass.utility.ReadFile - Read File Error: Fail to read file: /scratch/gencore/ma5877/small_RNA/COMPSRA/bundle_v1/db/miRBase/miRBase_hg38.gff3.
15:59:45.968 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null
java.lang.NullPointerException
        at edu.harvard.channing.compass.utility.ReadFile.readGFF3(ReadFile.java:384)
        at edu.harvard.channing.compass.db.DB_miRBase.getForest(DB_miRBase.java:102)
        at edu.harvard.channing.compass.core.ann.IPTR_miRNA.buildForest(IPTR_miRNA.java:51)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.Annotate(SAMAnnotator.java:79)
        at edu.harvard.channing.compass.core.ann.SAMAnnotator.call(SAMAnnotator.java:160)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
15:59:46.001 [main] ERROR edu.harvard.channing.compass.core.ann.Annotation - java.lang.NullPointerException
15:59:46.001 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Annotation module fails!`

**Comment by cougarlj** [comment]
Dear mars188,

Thank you for using COMPSRA in your study. According to the error message, the problem should be the that the version of COMPSRA doesn't match the version of pre-built databases. To solve this problem, please download the latest version of COMPSRA and the pre-built databases from Github. Hope this can help you. 

Best Wishes,  
  Jiang Li

**Comment by mars188** [comment]
Dear Jiang, Thank you for getting back to me. 

downloaded the latest COMPSRA (COMPSRA_V1.0.3) and built-in databases as follows:
`java -jar COMPSRA.jar -tk -dr -ck miRNA_hg38`
`java -jar COMPSRA.jar -tk -dr -ck piRNA_hg38`

and so on.... but I get the same error again.

Could it be because of java? I am using the following java:
`java version "1.7.0_95"`
`OpenJDK Runtime Environment (rhel-2.6.4.0.el7_2-x86_64 u95-b00)`
`OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)`
 
Also the first two modules (QC and alignment) run just fine only error shows up at annotation stage. 

I would really appreciate your help!

**Comment by cougarlj** [comment]
Dear mars188,

Since you can run the first two models, the Java should be OK. I'm not sure whether you can download the pre-built databases successfully, because many users told me that they failed to do this. Fortunately, I have uploaded some databases to GitHub (https://github.com/cougarlj/COMPSRA/tree/master/bundle_v1/prebuilt_db). So, please download the target databases by yourself from GitHub and put them in the right directory in your Server. I think your problem should be solved.

Best Wishes,
  Jiang Li

**Comment by mars188** [comment]
Yes, this one worked. I downloaded the databases from GitHub page and put them in the right folder. That solved the issue. 

Thank you sooo much for your help.
