### ISSUE TITLE
rlh parameter

### ISSUE THREAD

**Issue by Ben7124** [cougarlj/COMPSRA#26]
Hello,

I have a question about the rlh parameter to divide the reads into length intervals. I notice in the example rlh is 8,17. Does this mean only reads of length 8-17 are passed on to the next module? How to use this rlh parameter properly?

Thanks!

**Comment by cougarlj** [comment]
Dear Ben7124,

Thank you for using COMPSRA. The -rhl 8,17 will divide reads into 0-7,8-16 and >17 three groups. In default, the last group >17 will be used in the next step. If you use -rhl 17 and it will divide reads into <17 and >17 group and the >17 group will be used in default. If you want to choose the group by yourself, you can use the parameter in alignment module with -midx which takes 0 as the first group and 1 as the second group, but this only function when the module run together. 
 
Thanks!
