### ISSUE TITLE
What dose the InCluster mean in the annotation file of pirna

### ISSUE THREAD

**Issue by liangwx332** [cougarlj/COMPSRA#35]

**Comment by liangwx332** [comment]
Hi

I used COMPSRA to gain the finally result of pirna, but I did not know the mean of InCluster  in the last column.


The results as following

DB      Name    ID      Count   InCluster
piRNABank|piRBase       hsa_piR_016658  DQ592931        74058   false
piRNABank|piRBase       hsa_piR_016659  DQ592932        22284   false
piRNABank|piRBase       hsa_piR_010541  DQ584197        2       false
piRBase piR-hsa-32235   -       6618    false
piRBase piR-hsa-26508   DQ596292        2100    false
piRBase piR-hsa-32236   -       31      true
piRNABank|piRBase       hsa_piR_004506  DQ576200        2       false
piRNABank|piRBase       hsa_piR_006308  DQ578624        1       false

**Comment by cougarlj** [comment]
Dear liangwx332,

The InCluster column comes from the database piRNAclusterDB in which the author defined piRNAs should be in clusters. So, false means this piRNA is not in the clusters defined in piRNAclusterDB and true means yes. You can refer to the original paper of piRNAclusterDB. Currently, COMPSRA uses the 1.0 version of piRNAclusterDB.

Best Wishes,
  Jiang Li

**Comment by liangwx332** [comment]
> Dear liangwx332,
> 
> The InCluster column comes from the database piRNAclusterDB in which the author defined piRNAs should be in clusters. So, false means this piRNA is not in the clusters defined in piRNAclusterDB and true means yes. You can refer to the original paper of piRNAclusterDB. Currently, COMPSRA uses the 1.0 version of piRNAclusterDB.
> 
> Best Wishes, Jiang Li


Hi,

Thank you very much for your help

Best wishes,
Liang Wei

**Comment by liangwx332** [comment]
Hi，

I have an another question. Because  speed of downloading star and hg38 genome is  slow. So I could use my star to construct index, then use my star to align to genome  but alignment parameters  provided by your, finally use your scripts to annotation the alignment results. Code as following

**Buildind indexes :**  STAR --genomeDir . --genomeFastaFiles hg38.fa --runMode genomeGenerate --runThreadN 3

**Alingment:**  STAR  --runThreadN 4 --runMode alignReads  --outSAMtype BAM Unsorted  --outSAMattributes Standard  --readFilesCommand zcat  --outSAMunmapped Within  --outReadsUnmapped None  --alignEndsType Local --outFilterMismatchNmax 1 --alignIntronMax 1  --alignIntronMin 2 --outFilterMultimapScoreRange 1  --outFilterScoreMinOverLread 0.66  --outFilterMatchNminOverLread 0.66  --outFilterMismatchNoverLmax 0.05  --outFilterMatchNmin 16  --outFilterMultimapNmax 1000000 --genomeDir /home/liangwei/project/1.pimran/index/test  --readFilesIn /home/liangwei/project2/3.tri_clean/M9_raw_trimmed.fq.gz --outFileNamePrefix M9_raw_ &> M9_raw.log 

annonation:  java -jar COMPSRA.jar -ref hg38 -ann -ac 1,2,3,4,5,6 -in ~/project2/7.clean_star/test/M9_raw_Aligned.out.bam -out ~/project2/7.clean_star/test/M9_raw_Aligned

Best wishes,
Liang Wei

**Comment by cougarlj** [comment]
Dear liangwx332,

That should be fine. Otherwise, you can put STAR in the COMPSRA directory
and change the name into version 2.5. So what's your question?

Best Wishes,
  Jiang Li

**Comment by liangwx332** [comment]
Dear  Jiang Li,
I'm really sorry for replying so late

Thank you very much for your reply. My question is whether I can align with the star I downloaded instead of the star provided by the software, and you have told me.

Best wishes,
Liang Wei
