### ISSUE TITLE
SAMAnnotator - null

### ISSUE THREAD

**Issue by Stakaitis** [cougarlj/COMPSRA#37]
**Issue**:
Annotation step fails due to error: `ERROR edu.harvard.channing.compass.core.ann.SAMAnnotator - null`

**Version**:
Probably V1.0.2 2020-07-03 (as stated in log.txt)
But I downloaded COMPSRA from github -> `wget https://github.com/cougarlj/COMPSRA/raw/master/COMPSRA_V1.0.3.zip`

**Command**:
[run.txt](https://github.com/cougarlj/COMPSRA/files/8491923/run.txt) file

**Log**:
[log.txt](https://github.com/cougarlj/COMPSRA/files/8491927/log.txt) file

**Question**:
How to avoid this error?

**Comment by cougarlj** [comment]
Dear Rytis,

Sorry for the late reply. According to your command and log files, I guess
the problem may be the parameter "--ann_class A1,A2,A3" which should be
"--ann_class 1,2,3". If it doesn't work, please let me know.

Best regards,
  Jiang Li
