### ISSUE TITLE
Issue during alignment/installation

### ISSUE THREAD

**Issue by jackbrougher** [cougarlj/COMPSRA#38]
Hello,

Thank you for providing the COMPSRA resource for usage. 

I'm in the process of installing and checking the installation process on an EC2 AWS server. Currently I'm running into an issue at the example alignment step, and I'm assuming it has to do with the previous installation of STAR. Error message copied below, any thoughts or suggestions?

/newvolume/COMPSRA/bundle_v1/plug/star/STAR-2.5.3a/bin/Linux_x86_64/STAR: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
Fail to call: /newvolume/COMPSRA/bundle_v1/plug/star/STAR-2.5.3a/bin/Linux_x86_64/STAR --runThreadN 4 --runMode alignReads  --outSAMtype BAM Unsorted  --outSAMattributes Standard  --readFilesCommand zcat  --outSAMunmapped Within  --outReadsUnmapped None  --alignEndsType Local --outFilterMismatchNmax 1 --alignIntronMax 1  --alignIntronMin 2 --outFilterMultimapScoreRange 1  --outFilterScoreMinOverLread 0.66  --outFilterMatchNminOverLread 0.66  --outFilterMismatchNoverLmax 0.05  --outFilterMatchNmin 16  --outFilterMultimapNmax 1000000 --genomeDir /newvolume/COMPSRA/bundle_v1/db/star/hg38 --readFilesIn /newvolume/COMPSRA/example_out/sample01/sample01_17to50_FitRead.fastq.gz --outFileNamePrefix /newvolume/COMPSRA/example_out/sample01/sample01_17to50_FitRead_STAR_

**Comment by jackbrougher** [comment]
Figured it out

**Comment by cougarlj** [comment]
That's great. If you have any problem about using COMPSRA, please let me know.
