### ISSUE TITLE
Show sequence in annotation file

### ISSUE THREAD

**Issue by genericname2** [cougarlj/COMPSRA#43]
Hi again,

First, thanks again for this amazing tool, it really speeded up my small RNA analysis and the QC module, the Alignment module as well as the annotation module work fine on MacOS after some troubleshooting.

I now have another request: Is there an option to show the sequences of the annotated small RNAs in the .txt output file of the annotation module? I know, I can get the sequence from the databases, but I think it would be convenient to have them in .txt file to begin with.

Thanks for your support!

**Comment by cougarlj** [comment]
Dear genericname2,

Sorry to reply late. There are two parameters "-ad" and "-abam" that you can try in the annotation module. Some detailed info in bam or txt file will be output for debug purpose. Hope this can help you. 

Best Wishes,
  Jiang Li

**Comment by genericname2** [comment]
Dear Jiang Li,

I tried both parameters, but they did not exactly give me what I was looking for (the reference sequence of each small RNA in an individual column). However, as the workaround is quite simple, don't bother with it. I got my fasta sequences from mirBase and added them by a simple bash script.

Thanks anyway!
