### ISSUE TITLE
Zip file still has COMPSRA V1.0.2

### ISSUE THREAD

**Issue by Ben7124** [cougarlj/COMPSRA#44]
Hello,

The zip file COMPSRA_V1.0.3.zip still has version 1.0.2 shown below. Where can I download V1.0.3? Thank you.
+++++++++++++++++++++++++++++++
+            COMPSRA          +
+     (V1.0.2 2020-07-03)     +
+  rejia@channing.harvard.edu +
+++++++++++++++++++++++++++++++

**Comment by cougarlj** [comment]
Dear Ben7124,

Sorry for the late reply. Currently COMPSRA in GitHub is already the newest
version. The message shown on the screen is forgotten to be updated. Sorry
for that. COMPSRA2 is planned to be released this autumn.

Best Wishes,
  Jiang
