### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by kboufea** [cougarlj/COMPSRA#7]
Hi, I am trying to download COMPSRA from your website but I get a 500 internal server error. Could you have a look at this please?

Katerina

**Comment by cougarlj** [comment]
Dear Katerina,

Thanks a lot for the response. The IT department just updated the system last Sunday and they may forget to open the web server. I will send email to tell them the problem. 

Best Wishes,
  Jiang

**Comment by kboufea** [comment]
Dear Jiang, 

Many thanks for looking into it. Do you have any estimate on when the server might be up and running again?

Thank you, 
Katerina

**Comment by cougarlj** [comment]
Hi, Katerina,

The IT group has started to fix this problem. I think they should solve this during this week. 

Best Wishes,
  Jiang

**Comment by kboufea** [comment]
Hi Jiang, 

I can confirm the server is running again and I have been able to donwload and run COMPSRA!
Many thanks for the promt help!

Best, 
Katerina
