### ISSUE TITLE
Start and End position of small RNAs

### ISSUE THREAD

**Issue by mariah9875** [cougarlj/COMPSRA#8]
Hello. I am working with the Annotation module of COMPSRA, and I was wondering if I could extract somehow the location of the small RNAs that are in the annotation report (countfile)?

All the best,
María

**Comment by cougarlj** [comment]
Dear Maria,

The annotation report only provides how many different types of RNAs are annotated by reads. If you want to extract the small RNAs by location, you can refer to the gff3 files (https://regepi.bwh.harvard.edu/circurna/bundle_v1/db/miRBase/miRBase_hg38.gff3). 

Best Wishes,
  Jiang Li

**Comment by mariah9875** [comment]
Thank you so much for this information Jiang Li! 

All the best,
María

**Comment by cougarlj** [comment]
You are welcome.

**Comment by mariah9875** [comment]
Hello, I ran the Annotation module of COMPSRA and I do not get Ids for miRNA, snRNA, and snoRNA in my output countfiles. Instead, the id column has an - symbol instead. Is there a possibility to get the gene_ids in the countfiles? 

All the best,
María
