### ISSUE TITLE
Problem with alignment using hg19

### ISSUE THREAD

**Issue by drumair** [cougarlj/COMPSRA#9]
While using alignment mode using hg19, I am getting following error. 

08:42:02.883 [main] INFO  java.lang.Class - To run: /home/ubuntu/COMPSRA/bundle_v1/plug/star/STAR-2.5.3a/bin/Linux_x86_64/STAR --runMode genomeGenerate --runThreadN 4  --genomeDir /home/ubuntu/COMPSRA/bundle_v1/db/star/hg19 --genomeFastaFiles /home/ubuntu/COMPSRA/bundle_v1/db/star/hg19/hg19.fa.gz
Dec 08 08:42:02 ..... started STAR run
Dec 08 08:42:02 ... starting to generate Genome files

EXITING because of INPUT ERROR: the file format of the genomeFastaFile: /home/ubuntu/COMPSRA/bundle_v1/db/star/hg19/hg19.fa.gz is not fasta: the first character is '' (31), not '>'.
 Solution: check formatting of the fasta file. Make sure the file is uncompressed (unzipped).

Dec 08 08:42:02 ...... FATAL ERROR, exiting
08:42:02.904 [pool-2-thread-1] INFO  java.lang.Class - To run: /home/ubuntu/COMPSRA/bundle_v1/plug/star/STAR-2.5.3a/bin/Linux_x86_64/STAR --runThreadN 4 --runMode alignReads  --outSAMtype BAM Unsorted  --outSAMattributes Standard  --readFilesCommand zcat  --outSAMunmapped Within  --outReadsUnmapped None  --alignEndsType Local --outFilterMismatchNmax 1 --alignIntronMax 1  --alignIntronMin 2 --outFilterMultimapScoreRange 1  --outFilterScoreMinOverLread 0.66  --outFilterMatchNminOverLread 0.66  --outFilterMismatchNoverLmax 0.05  --outFilterMatchNmin 16  --outFilterMultimapNmax 1000000 --genomeDir /home/ubuntu/bundle_v1/db/star/hg19 --readFilesIn /home/smallrnaseq/raw/An_T_R1/An_T_R1_17to51_FitRead.fastq.gz --outFileNamePrefix /home/smallrnaseq/raw/An_T_R1/An_T_R1_17to51_FitRead_STAR_

EXITING because of FATAL ERROR: could not create output file: /home/smallrnaseq/raw/An_T_R1/An_T_R1_17to51_FitRead_STAR_Log.out
Check if the path /home/smallrnaseq/raw/An_T_R1/An_T_R1_17to51_FitRead_STAR_ exists and you have permissions to write there

Dec 08 08:42:02 ...... FATAL ERROR, exiting
08:42:02.908 [pool-2-thread-1] ERROR edu.harvard.channing.compass.core.Factory - /home/smallrnaseq/raw/An_T_R1/An_T_R1_17to51_FitRead_AlnReport.txt (No such file or directory)
08:42:02.909 [main] INFO  edu.harvard.channing.compass.core.aln.Alignment - java.lang.NullPointerException
08:42:02.909 [main] INFO  edu.harvard.channing.compass.core.Produce - Error: Alignment module fails!

**Comment by cougarlj** [comment]
Please try to use gunzip command to un-compress the file hg19.fa.gz. I guess STAR can only accept hg19.fa file.

**Comment by drumair** [comment]
I tried using gunzip, and deleted the hg19.fa.gz file, but it searches for the same, whereas when I use hg38 ref, it directly uses hg38.fa

10:09:05.039 [main] INFO  java.lang.Class - To run: /apps/comsra/COMPSRA-master/bundle_v1/plug/star/STAR-2.5.3a/bin/Linux_x86_64/STAR --runMode genomeGenerate --runThreadN 4  --genomeDir /opt/apps/comsra/COMPSRA-master/bundle_v1/db/star/hg38 --genomeFastaFiles /opt/apps/comsra/COMPSRA-master/bundle_v1/db/star/hg38/hg38.fa

**Comment by cougarlj** [comment]
There may be a bug for hg19. So, anyway, you can directly run STAR using the command, but not through COMPSRA for this step. Please directly run the command  (/home/ubuntu/COMPSRA/bundle_v1/plug/star/STAR-2.5.3a/bin/Linux_x86_64/STAR --runMode genomeGenerate --runThreadN 4 --genomeDir /home/ubuntu/COMPSRA/bundle_v1/db/star/hg19 --genomeFastaFiles /home/ubuntu/COMPSRA/bundle_v1/db/star/hg19/hg19.fa)

If it doesn't work, please let me know.

**Comment by drumair** [comment]
It works, thanks.
